theme: minima
title: Talk about your resume
author: etiennebramley
email: etienne.bramley@gmail.com
description: > # Resume discussion
  Let's talk about what to include in our resumes and what not. 
  Improving your resume will improve your chances for getting a job.
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  etiennebramley

show_excerpts: false # set to false to remove excerpts on the homepage
